#pragma once

#define WM_HIDE_COMBOLIST (WM_USER + 100)
#define WM_COMBOLIST_KILLFOCUS (WM_USER + 105)
#define WM_NATIVECOMBO_SETFOCUS (WM_USER + 115)
#define WM_NATIVECOMBO_KILLFOCUS (WM_USER + 120)
#define WM_COMBOEDIT_CLICK (WM_USER + 110)
#define WM_COMBOEDIT_KILLFOCUS (WM_USER + 125)
//#define WM_COMBOLIST_MOUSECLOSE (WM_USER + 130)
#define WM_MOUSECLICK_CHECK (WM_USER + 135)
#define WM_COMBOLIST_SELENDOK (WM_USER + 140)
#define WM_TEMPLATE_SEARCH_FINISHED (WM_USER + 145)
#define WM_TEMPLATE_SEARCH_CANCELLED (WM_USER + 150)
#define WM_TEMPLATE_SEARCH_STARTED (WM_USER + 155)
#define WM_DATACOMBO_UNLOCK (WM_USER + 160)
#define WM_DATACOMBO_SETCURSEL (WM_USER + 165)
#define WM_DATACOMBO_SETTRUECONTENT (WM_USER + 170)
#define WM_DATACOMBO_SET_MATCHING_CONTENT (WM_USER + 175)
#define WM_DATACOMBO_REFRESH_DISPLAY_CONTENT (WM_USER + 180)
#define WM_DATACOMBO_DISPLAY_LOCK (WM_USER + 185)
#define WM_DATACOMBO_DISPLAY_UNLOCK (WM_USER + 190)

#define SEARCH_TEMPLATE_DELAY 500
#define SEARCH_TEMPLATE_TIMER_ID 1

#define DEFAULT_SEARCH_LABEL "Идет поиск..."

#define LIST_PROGRESS_DELAY 10
#define LIST_PROGRESS_TIMER_ID 3